import os
from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
import tempfile
from reportlab.lib import colors

def convert_currency(amount, to_currency='USD'):
    """
    Dummy currency converter.
    Base currency is assumed to be USD for the generated data.
    """
    rates = {
        'USD': 1.0,
        'INR': 83.0,
        'AED': 3.67,
        'EUR': 0.92,
        'GBP': 0.79
    }
    
    rate = rates.get(to_currency, 1.0)
    converted = amount * rate
    
    symbols = {
        'USD': '$',
        'INR': '₹',
        'AED': 'AED',
        'EUR': '€',
        'GBP': '£'
    }
    return converted, symbols.get(to_currency, '$')

def generate_pdf_report(patient_details, cost_predictions):
    """
    Generate a PDF report for the medical tourism cost prediction.
    """
    temp_dir = tempfile.gettempdir()
    pdf_path = os.path.join(temp_dir, "medical_budget_report.pdf")
    
    c = canvas.Canvas(pdf_path, pagesize=letter)
    width, height = letter
    
    # Title
    c.setFont("Helvetica-Bold", 20)
    c.drawString(180, height - 50, "Medical Tourism Budget Report")
    
    # Patient Details Section
    c.setFont("Helvetica-Bold", 14)
    c.drawString(50, height - 100, "Patient Details:")
    
    c.setFont("Helvetica", 12)
    y_pos = height - 120
    for key, value in patient_details.items():
        c.drawString(70, y_pos, f"{key}: {value}")
        y_pos -= 20
        
    # Cost Prediction Section
    c.setFont("Helvetica-Bold", 14)
    c.drawString(50, y_pos - 20, "Estimated Costs:")
    
    c.setFont("Helvetica", 12)
    y_pos -= 40
    
    for key, value in cost_predictions.items():
        c.drawString(70, y_pos, f"{key}: {value}")
        y_pos -= 20
        
    # Footer
    c.setFont("Helvetica-Oblique", 10)
    c.drawString(50, 50, "Disclaimer: These are estimated costs generated by AI. Actual costs may vary.")
    
    c.save()
    return pdf_path

def get_hospital_recommendation(disease, country, hospital_type):
    # Dummy recommendations based on input
    recs = [
        f"Global Health Center, {country} (Best for {disease})",
        f"Care Premium Hospital, {country} ({hospital_type} Specialty)",
        f"Advanced Medical Institute, {country}"
    ]
    return recs

def get_best_city_recommendation(disease):
    recs = {
        'Heart Bypass': ['Bangkok', 'Singapore', 'USA'],
        'Oncology Treatment': ['Germany', 'USA', 'UK'],
        'Cosmetic Surgery': ['Seoul', 'Dubai', 'Istanbul']
    }
    return recs.get(disease, ['Mumbai', 'Kuala Lumpur', 'Dubai'])
